### ISSUE TITLE
Streaming XML Parsing

### ISSUE THREAD

**Issue by tedsteiner** [tedsteiner/OpenStreetMap.jl#35]
Currently OpenStreetMap.jl parses OSM datafiles using LightXML.jl, which loads the entire file into memory. Because we only access each element once and then close the file, it would be much more efficient to use a streaming XML parser instead, especially when reading from large datafiles.

I'm not sure why, but loading a 150 MB .osm file takes up a couple GB of RAM, so anything much larger than a city isn't really feasible right now.

**Comment by yeesian** [comment]
closed via #55
