### ISSUE TITLE
Change link to the docs, warn about unreleased master.

### ISSUE THREAD

**Issue by michal-gh** [tedsteiner/OpenStreetMap.jl#70]
The documentation available on readthedocs site is out of sync with released package. The Pkg.add installs v0.7, but the GitHub link points to the documentation about the latest, unreleased version. 
I installed the package through standard Pkg.add call, but then followed the link to the documentation of the new version. Needless to say, I've had a lot of problems understanding why getOSMData() doesn't work.
I think it'd be better to link to "stable" version of the documentation and warn users that the current, fairly old master branch is not released yet.

**Comment by tedsteiner** [comment]
Thank you for letting us know! I didn't realize this, but I'm sorry that it was confusing. I agree with you, and I'll change the documentation link very soon (I'll be pushing out version 0.8 later this week so I'll just make the fix then).
