### ISSUE TITLE
Problem in clustering intersections

### ISSUE THREAD

**Issue by liyan2015** [tedsteiner/OpenStreetMap.jl#78]
Hi,

I'm running OpenStreetMap.jl in Julia 0.3.10 x64 on Win 7. When I was using the below code to filter and cluster intersections:

nodes, hwys, builds, feats = getOSMData(MAP_FILENAME)
highway_sets = findHighwaySets(hwys)
intersection_mapping = findIntersectionClusters(nodes,intersections,highway_sets,max_dist=15)

Julia shows 

ERROR: 'findIntersectionCluster' has no method matching findIntersectionClusters(::Dict{Int64,LLA}, ::Dict{Int64,Intersection}, ::Array{HighwaySet,1})

In intersections.jl, it shows:

function findIntersectionClusters( nodes::Dict{Int,ENU}, 
                                   intersections_in::Dict{Int,Intersection}, 
                                   highway_clusters::Vector{HighwaySet}; 
                                   max_dist=15.0 )

It seems 'findIntersectionCluster' does not accept input (Dict, Dict, Array), or OpenStreetMap.jl does not support 64-bit?  Any suggestion is appreciated. Thanks!

**Comment by liyan2015** [comment]
My bad, ENU(nodes::Dict{Int,LLA}, reference::LLA) is needed to convert LLA to ENU first....

Perhaps it's worth mentioning in the document?

**Comment by tedsteiner** [comment]
Thanks for pointing that out, I'll update the documentation soon!
