### ISSUE TITLE
factor coordinates into separate package?

### ISSUE THREAD

**Issue by StefanKarpinski** [tedsteiner/OpenStreetMap.jl#9]
Since physical global coordinates are such a fundamental thing and not really specific to OpenStreetMap, it may make sense to factor the coordinates code out into its own package. A good example of this sort of thing is the `Color` package, which implements a huge amount of colorimetry functionality: https://github.com/JuliaLang/Color.jl.

**Comment by garborg** [comment]
I'm about done splitting out existing coordinate functionality into `Geodesy.jl` and tightening up the code. Is `JuliaGeospatial` a good organization name? Should we wait to create an organization until the ecosystem is fleshed out a little more?

**Comment by yeesian** [comment]
including some of the julia-geo developers here: @wkearn @meggart

**Comment by wkearn** [comment]
I'm all for more/better geospatial tools in Julia. We do have a mailing list for this kind of thing (julia-geo@googlegroups.com), but it hasn't seen much activity lately. It's not particularly well-advertised for one. 

I haven't been working too much with geospatial stuff lately (my [GDAL.jl](https://github.com/wkearn/GDAL.jl) has languished over the last few months), but if there is interest in beefing up the Julia geospatial infrastructure, I'll contribute where I can.

**Comment by yeesian** [comment]
@garborg when you're ready, maybe post an announcement about `Geodesy.jl` to the [julia-geo mailing list](https://groups.google.com/forum/#!forum/julia-geo)?

@wkearn, I have been working with `shapely`/`fiona`/`geopandas` in python, and am interested in the `GDAL` package too, but have my hands busy with other packages. What's your take on first priorities for JuliaGeo[spatial], or your package on [JuliaGIS](https://github.com/wkearn/GIS.jl)?

**Comment by garborg** [comment]
@yeesian Good idea -- posted.

**Comment by yeesian** [comment]
closed by #61
